services:
  elasticsearch:
    image: elasticsearch:8.9.2
    container_name: elasticsearch
    mem_limit: 2048m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./ELK/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - TZ=Europe/Amsterdam
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      atomic:
        ipv4_address: 172.18.0.2

  logstash:
    image: logstash:8.9.2
    container_name: logstash
    mem_limit: 2048m
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./ELK/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./ELK/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - TZ=Europe/Amsterdam    
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      atomic:
        ipv4_address: 172.18.0.3
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.9.2
    container_name: kibana
    mem_limit: 2048m
    ports:
      - "5601:5601"
    volumes:
      - ./ELK/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - TZ=Europe/Amsterdam    
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"      
    networks:
      atomic:
        ipv4_address: 172.18.0.4
    depends_on:
      - elasticsearch

networks:
  atomic:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1